# Generated by Django 3.2.23 on 2024-11-18 18:47

import applications.models.base
import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0050_auto_20241113_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.base.resume_path_hackers, validators=[applications.validators.validate_file_extension]),
        ),
    ]
